# Generated by Django 4.0.4 on 2022-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250, null=True)),
                ('Task', models.TextField()),
                ('Status', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModiefiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
