# Generated by Django 4.0.4 on 2022-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToAdd', '0002_alter_listtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtask',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed')], default='Pending', max_length=250),
        ),
    ]
