# Generated by Django 4.0.4 on 2022-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToAdd', '0004_listtask_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtask',
            name='Expired',
            field=models.BooleanField(default=False),
        ),
    ]
