# Generated by Django 4.0.4 on 2022-05-09 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToAdd', '0006_alter_listtask_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtask',
            name='DueDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
